version: "3.5"

services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    container_name: "zookeeper"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  producer:
    build:
      context: .
      dockerfile: DockerfileProducer
    container_name: "producer"
    ports:
      - "3000:3000"
    depends_on:
      - kafka
  
  consumer:
    build:
      context: .
      dockerfile: DockerfileConsumer
    container_name: "consumer"
    depends_on:
      - kafka
    restart: always

  kafka:
    image: bitnami/kafka:2.5.0
    container_name: "kafka"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.8.103:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  init-kafka:
    image: bitnami/kafka:2.5.0
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:9092 ---create --topic comments --replication-factor 1 --partitions 1


      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:9092 --list
      "